### ISSUE TITLE
where is action_list.csv?

### ISSUE THREAD

**Issue by WXLL579** [whyang78/iCAN_PyTorch#1]
Thanks for your work. I wonder where is action_list.csv? or is there some code to build it ?

**Comment by whyang78** [comment]
> Thanks for your work. I wonder where is action_list.csv? or is there some code to build it ?

I hava changed this project, the file has been uploaded.

**Comment by whyang78** [comment]
I hava changed this project, the file has been uploaded.



At 2021-11-02 14:17:44, "WXLL579" ***@***.***> wrote:

Thanks for your work. I wonder where is action_list.csv? or is there some code to build it ?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by WXLL579** [comment]
thanks!

**Comment by WXLL579** [comment]
sorry to bother you.. but where is 'iter_0.pkl' in ts_ResNet_HICO.py ? Thanks ! 👍
